### PR TITLE
Fixes #50

### LINKED ISSUE #50: Can't install since newest Amazon Update (5.0.5.1)
I got pushed an Amazon update this morning, and I can't get FireStarter to install at all.  Had it working well until the newest update (5.0.5.1), but all traces of it seem wiped from my FTV2.  Have tried both methods (ES Explorer and adb).  

When running the last step, adb gives: 

``` code
Starting: Intent { cmp=de.belu.firestarter/.gui.MainActivity }
Error type 3
Error: Activity class {de.belu.firestarter/de.belu.firestarter.gui.MainActivity} does not exist.

```

### PR DESCRIPTION
**Pull request by jkchr1s**
- Renamed package to de.belu.firestopper to prevent Amazon blacklist
- Bundle adb since Amazon removed it for home button detection (fallback method was not working on 5.0.5.1)
- Bumped minimum sdk version (couldn't target 2.1 anymore with Android Studio on my Mac)

### CODE REVIEW

**Comment by ralle12345** [comment]
Works for me!

**Comment by infinityhaitian** [comment]
We need to be smarter than Amazon..

**Comment by xcsrz** [comment]
> We need to be smarter than Amazon..

Amazon has taken aim at this project.  Renaming the package is just a bandaid.  One that will likely need to be redone to match every update to the OS.

What we really need is a usable replacement ROM.

**Comment by pquerner** [comment]
Works +1

(installed APK via adbFire)

**Comment by rprimus** [comment]
Sat Apr  9 14:21:06 BST 2016

For anyone interested,  here are the logs for installation (failure) of FireStarter:

``` irc
D/DefContainer( 3844): Copying /data/local/tmp/FireStarter-v3.2.3.apk to base.apk
W/CompatManager(  469): The Zip file converted from the apk is empty
W/CompatManager(  469): Cannot read compat file in assert dir
D/PackageManager(  469): Renaming /data/app/vmdl486828472.tmp to /data/app/de.belu.firestarter-2
W/CompatManager(  469): failed deleting the hint file for package de.belu.firestarter
I/ActivityManager(  469): Force stopping de.belu.firestarter appid=10001 user=-1: uninstall pkg
I/PackageManager(  469): Package de.belu.firestarter codePath changed from /data/app/de.belu.firestarter-1 to /data/app/de.belu.firestarter-2; Retaining data and using new
I/PackageManager(  469): Derived cpuAbiOverride=null
D/PackageManager(  469): Resolved nativeLibraryRoot for de.belu.firestarter to root=/data/app/de.belu.firestarter-2/lib, isa=true
D/PackageManager(  469): Abis for package[de.belu.firestarter] are primary=null secondary=null
I/PackageManager(  469): Running dexopt on: /data/app/de.belu.firestarter-2/base.apk pkg=de.belu.firestarter isa=arm vmSafeMode=false
I/ActivityManager(  469): Force stopping de.belu.firestarter appid=10001 user=-1: update pkg
W/PackageManager(  469): Code path for pkg : de.belu.firestarter changing from /data/app/de.belu.firestarter-1 to /data/app/de.belu.firestarter-2
W/PackageManager(  469): Resource path for pkg : de.belu.firestarter changing from /data/app/de.belu.firestarter-1 to /data/app/de.belu.firestarter-2
W/CompatManager(  469): The Zip file converted from the apk is empty
I/ActivityManager(  469): Force stopping de.belu.firestarter appid=10001 user=0: pkg removed
I/RegisteredPolicyManager(  469): user/package action=android.intent.action.PACKAGE_REMOVED     userHandle0
I/RegisteredPolicyManager(  469): user/package action=android.intent.action.PACKAGE_ADDED       userHandle0
I/RegisteredPolicyManager(  469): user/package action=android.intent.action.PACKAGE_REPLACED    userHandle0
W/RegisteredPolicyManager(  469): Metadata not available in package:de.belu.firestarter
I/RegisteredPolicyManager(  469): Package removed:de.belu.firestarter
```

**Comment by xadamxk** [comment]
So what APK do I install that still works?

**Comment by meliton** [comment]
Firestopper will work until Amazon blacklists it. So far, firestopper is still working.

**Comment by aistis-** [comment]
Is it possible to make package name randomized each time you install an apk?

**Comment by meliton** [comment]
The installation location is tied to the directory structure of the apk. When `de.belu.firestarter` is installed, it exists as a directory in `/data/data/de/belu/firestarter` of the firestick. Programmatic calls to functions in firestarter resolve to that directory. To randomize the installation package would be to randomize the package (folders) that firestarter would be in and that isn't possible AFAIK. I refactored my version of firestarter/firestopper into another directory that is unknown to Amazon so I'm confident it'll survive the next update.

**Comment by infinityhaitian** [comment]
hey the double click home key on firestarter is not working, and i can't
import files, it says errors after importing.. please help

**Comment by meliton** [comment]
@infinityhaitian, the double home key is currently broken with the 5.0.5.1 update. Your best bet is to use firestopper but double home is broken there as well.

**Comment by infinityhaitian** [comment]
When will this be fixed, just asking.

**Comment by infinityhaitian** [comment]
No fix yet

**Pull request closed without merging**
